
[functions.odoo-sync]
enabled = true
verify_jwt = false
import_map = "./functions/odoo-sync/deno.json"
entrypoint = "./functions/odoo-sync/index.ts"

[functions.odoo-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/odoo-webhook/index.ts"

[functions.odoo-polling]
enabled = true
verify_jwt = true
import_map = "./functions/odoo-polling/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/odoo-polling/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/odoo-polling/*.html" ]

[functions.exec-sql]
enabled = true
verify_jwt = true
import_map = "./functions/exec-sql/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/exec-sql/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/exec-sql/*.html" ]

[functions.odoo-invite]
enabled = true
verify_jwt = false
import_map = "./functions/odoo-invite/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/odoo-invite/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/odoo-invite/*.html" ]
