-- =============================================================================
-- REPARA_TODO_DEV (Versión Incremental / Migración)
-- =============================================================================
-- Este script REPARA el esquema existente sin borrar tablas.
-- Ideal para entornos donde ya hay datos parciales.
-- =============================================================================

BEGIN;

-- 1. EXTENSIONES BÁSICAS
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. REPARACIÓN DE TABLAS BASE (Idempotente)
CREATE TABLE IF NOT EXISTS public.games (
    game_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_name   TEXT NOT NULL,
    game_code   TEXT NOT NULL UNIQUE,
    is_active   BOOLEAN DEFAULT true,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- REPAIR: Asegurar auto-incremento (Identity) en games
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'games' AND column_name = 'game_id' AND is_identity = 'NO') THEN
        ALTER TABLE public.games ALTER COLUMN game_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.sets (
    set_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id     INTEGER REFERENCES public.games(game_id) ON DELETE CASCADE,
    set_name    TEXT NOT NULL,
    set_code    TEXT NOT NULL UNIQUE,
    release_date DATE,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- REPAIR: Asegurar auto-incremento (Identity) en sets
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'sets' AND column_name = 'set_id' AND is_identity = 'NO') THEN
        ALTER TABLE public.sets ALTER COLUMN set_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- 3. MÓDULO DE ACCESORIOS (Adición Segura)
CREATE TABLE IF NOT EXISTS public.accessories (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    category    TEXT NOT NULL DEFAULT 'accessories',
    brand       TEXT,
    price       NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    stock       INTEGER NOT NULL DEFAULT 0,
    image_url   TEXT,
    game        TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    sku         TEXT,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- Garantizar restricciones únicas en accesorios para permitir ON CONFLICT
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'accessories_name_key') THEN
        ALTER TABLE public.accessories ADD CONSTRAINT accessories_name_key UNIQUE (name);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'accessories_sku_key') THEN
        ALTER TABLE public.accessories ADD CONSTRAINT accessories_sku_key UNIQUE (sku);
    END IF;
END $$;

-- 4. INTEGRACIÓN DE CARRITO (Incremental)
-- Asegurar que cart_items existe (el esquema base ya debería tenerlo)
CREATE TABLE IF NOT EXISTS public.cart_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    cart_id UUID NOT NULL,
    product_id UUID,
    quantity INTEGER NOT NULL DEFAULT 1
);

-- Añadir columna de accesorios si no existe
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'cart_items' AND column_name = 'accessory_id') THEN
        ALTER TABLE public.cart_items ADD COLUMN accessory_id UUID REFERENCES public.accessories(id) ON DELETE CASCADE;
    END IF;
END $$;

-- Añadir restricción de integridad de tipo (Solo uno: producto o accesorio)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_cart_item_has_one_type') THEN
        ALTER TABLE public.cart_items ADD CONSTRAINT chk_cart_item_has_one_type 
        CHECK ((product_id IS NOT NULL AND accessory_id IS NULL) OR (product_id IS NULL AND accessory_id IS NOT NULL));
    END IF;
END $$;

-- 5. SEMILLAS (Idempotentes)
INSERT INTO public.games (game_name, game_code) VALUES 
('Magic: The Gathering', 'MTG'),
('Pokémon TCG', 'POKEMON')
ON CONFLICT (game_code) DO NOTHING;

INSERT INTO public.accessories (name, description, category, brand, price, stock, game, is_active, sku)
VALUES
  ('Dragon Shield Matte Black', 'Protectores de alta calidad.', 'sleeves', 'Dragon Shield', 12.99, 50, NULL, true, 'DS-BLK'),
  ('Ultra Pro Satin Tower', 'Caja de mazo premium.', 'deck_box', 'Ultra Pro', 14.50, 20, NULL, true, 'UP-SATIN')
ON CONFLICT (name) DO NOTHING;

-- 6. ADMINISTRACIÓN DE USUARIOS (Admin Repair)
DO $$
DECLARE
  v_admin_id UUID := '00000000-0000-0000-0000-000000000001';
  v_admin_email TEXT := 'admin@geeko.com';
  v_admin_pass TEXT := 'admin123';
BEGIN
  -- Intentar crear el usuario en auth.users si no existe
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = v_admin_email) THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role)
    VALUES (
      v_admin_id, 
      v_admin_email, 
      crypt(v_admin_pass, gen_salt('bf')), 
      now(), 
      '{"provider":"email","providers":["email"]}', 
      '{}', 
      'authenticated', 
      'authenticated'
    );
  END IF;

  -- Asegurar que el perfil tiene rol admin
  INSERT INTO public.profiles (id, role)
  VALUES ((SELECT id FROM auth.users WHERE email = v_admin_email), 'admin')
  ON CONFLICT (id) DO UPDATE SET role = 'admin';
END $$;

COMMIT;
