-- =============================================================================
-- REPARA_TODO_DEV (Versión Incremental / Migración)
-- =============================================================================
-- Este script REPARA el esquema existente sin borrar tablas.
-- Ideal para entornos donde ya hay datos parciales.
-- =============================================================================

BEGIN;

-- 1. EXTENSIONES BÁSICAS
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. REPARACIÓN DE TABLAS BASE (Idempotente)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.games (
    game_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_name   TEXT NOT NULL,
    game_code   TEXT NOT NULL UNIQUE,
    is_active   BOOLEAN DEFAULT true,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sets (
    set_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id     INTEGER REFERENCES public.games(game_id) ON DELETE CASCADE,
    set_name    TEXT NOT NULL,
    set_code    TEXT NOT NULL UNIQUE,
    release_date DATE,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- 3. MÓDULO DE INVENTARIO (TCG + ACCESORIOS)
CREATE TABLE IF NOT EXISTS public.accessories (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    category    TEXT NOT NULL DEFAULT 'accessories',
    brand       TEXT,
    price       NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    stock       INTEGER NOT NULL DEFAULT 0,
    image_url   TEXT,
    game        TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    sku         TEXT UNIQUE,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- Definición de Productos (Singles)
CREATE TABLE IF NOT EXISTS public.products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    printing_id UUID NOT NULL,
    name TEXT,
    condition TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    image_url TEXT,
    set_code TEXT,
    finish TEXT DEFAULT 'nonfoil',
    updated_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT products_unique_item UNIQUE (printing_id, condition, finish)
);

-- 4. CARRITO Y ÓRDENES
CREATE TABLE IF NOT EXISTS public.carts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT DEFAULT 'Carrito Principal',
    is_active BOOLEAN DEFAULT true,
    is_pos BOOLEAN DEFAULT false,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cart_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    cart_id UUID NOT NULL REFERENCES public.carts(id) ON DELETE CASCADE,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,
    accessory_id UUID REFERENCES public.accessories(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    CONSTRAINT chk_cart_item_has_one_type CHECK (
        (product_id IS NOT NULL AND accessory_id IS NULL) OR 
        (product_id IS NULL AND accessory_id IS NOT NULL)
    ),
    CONSTRAINT cart_items_cart_product_key UNIQUE (cart_id, product_id),
    CONSTRAINT cart_items_cart_accessory_key UNIQUE (cart_id, accessory_id)
);

CREATE TABLE IF NOT EXISTS public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    total_amount NUMERIC NOT NULL DEFAULT 0,
    status TEXT DEFAULT 'pending',
    shipping_address JSONB,
    guest_info JSONB,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id UUID REFERENCES public.products(id),
    accessory_id UUID REFERENCES public.accessories(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    price_at_purchase NUMERIC NOT NULL,
    CONSTRAINT chk_order_item_type CHECK (
        (product_id IS NOT NULL AND accessory_id IS NULL) OR 
        (product_id IS NULL AND accessory_id IS NOT NULL)
    )
);

-- 5. SEMILLAS (Idempotentes)
INSERT INTO public.games (game_name, game_code) VALUES 
('Magic: The Gathering', 'MTG'),
('Pokémon TCG', 'POKEMON')
ON CONFLICT (game_code) DO NOTHING;

INSERT INTO public.accessories (name, description, category, brand, price, stock, game, is_active, sku)
VALUES
  ('Dragon Shield Matte Black', 'Protectores de alta calidad.', 'sleeves', 'Dragon Shield', 12.99, 50, NULL, true, 'DS-BLK'),
  ('Ultra Pro Satin Tower', 'Caja de mazo premium.', 'deck_box', 'Ultra Pro', 14.50, 20, NULL, true, 'UP-SATIN')
ON CONFLICT (name) DO NOTHING;

-- 6. ADMINISTRACIÓN DE USUARIOS (Admin Repair)
DO $$
DECLARE
  v_admin_id UUID := '00000000-0000-0000-0000-000000000001';
  v_admin_email TEXT := 'admin@geeko.com';
  v_admin_pass TEXT := 'admin123';
BEGIN
  -- Crear el usuario en auth.users si no existe
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = v_admin_email) THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, aud, role)
    VALUES (v_admin_id, v_admin_email, crypt(v_admin_pass, gen_salt('bf')), now(), 'authenticated', 'authenticated');
  END IF;

  -- Asegurar que el perfil tiene rol admin
  INSERT INTO public.profiles (id, role)
  VALUES ((SELECT id FROM auth.users WHERE email = v_admin_email), 'admin')
  ON CONFLICT (id) DO UPDATE SET role = 'admin';
END $$;

COMMIT;
